"""Updated RiotAccountInfoUser model

Revision ID: 68379449d174
Revises: 72aca240f4ab
Create Date: 2025-03-03 11:14:05.349049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68379449d174'
down_revision = '72aca240f4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riot_account_info_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solo_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('solo_wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('solo_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flex_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('flex_wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flex_losses', sa.Integer(), nullable=True))
        batch_op.drop_column('wins')
        batch_op.drop_column('tier')
        batch_op.drop_column('losses')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riot_account_info_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('flex_losses')
        batch_op.drop_column('flex_wins')
        batch_op.drop_column('flex_tier')
        batch_op.drop_column('solo_losses')
        batch_op.drop_column('solo_wins')
        batch_op.drop_column('solo_tier')

    # ### end Alembic commands ###
