"""Updated RiotAccountInfoUser model

Revision ID: 72aca240f4ab
Revises: 
Create Date: 2025-03-03 11:03:08.183102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72aca240f4ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riot_account_info_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riot_account_info_user', schema=None) as batch_op:
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
