"""Add tournament_teams association table

Revision ID: c3d2b1a9f8e7
Revises: 68379449d174
Create Date: 2025-11-05 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d2b1a9f8e7'
down_revision = '68379449d174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tournament_teams',
        sa.Column('tournament_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('tournament_id', 'team_id'),
        sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name='fk_tournament_teams_tournament_id'),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_tournament_teams_team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_teams')
    # ### end Alembic commands ###
